// tslint:disable
/**
 * Name Done - Name Service
 * A name service API for Name Done
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined } from '../runtime';
import type { OperationOpts, HttpQuery } from '../runtime';
import type {
    BadRequestResponseDto,
    NameResponseDto,
} from '../models';

export interface GetEmailDomainNamesRequest {
    name: string;
}

/**
 * no description
 */
export class EmailDomainNameApi extends BaseAPI {

    /**
     * Get a list of email domain names
     */
    getEmailDomainNames({ name }: GetEmailDomainNamesRequest): Observable<NameResponseDto>
    getEmailDomainNames({ name }: GetEmailDomainNamesRequest, opts?: OperationOpts): Observable<AjaxResponse<NameResponseDto>>
    getEmailDomainNames({ name }: GetEmailDomainNamesRequest, opts?: OperationOpts): Observable<NameResponseDto | AjaxResponse<NameResponseDto>> {
        throwIfNullOrUndefined(name, 'name', 'getEmailDomainNames');

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'name': name,
        };

        return this.request<NameResponseDto>({
            url: '/name/email-domain',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

}
