// tslint:disable
/**
 * Name Done - First Name Service
 * An first name service API for Name Done
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined } from '../runtime';
import type { OperationOpts, HttpQuery } from '../runtime';
import type {
    BadRequestResponseDto,
    NameResponseDto,
} from '../models';

export interface FamilyNameControllerGetRequest {
    name: string;
}

/**
 * no description
 */
export class FamilyNameApi extends BaseAPI {

    /**
     * Get a list of family names
     */
    familyNameControllerGet({ name }: FamilyNameControllerGetRequest): Observable<NameResponseDto>
    familyNameControllerGet({ name }: FamilyNameControllerGetRequest, opts?: OperationOpts): Observable<AjaxResponse<NameResponseDto>>
    familyNameControllerGet({ name }: FamilyNameControllerGetRequest, opts?: OperationOpts): Observable<NameResponseDto | AjaxResponse<NameResponseDto>> {
        throwIfNullOrUndefined(name, 'name', 'familyNameControllerGet');

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'name': name,
        };

        return this.request<NameResponseDto>({
            url: '/name/family',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

}
