// tslint:disable
/**
 * Name Done - Name Service
 * A name service API for Name Done
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NameResponseDto
 */
export interface NameResponseDto {
    /**
     * An array of possible first names
     * @type {Array<string>}
     * @memberof NameResponseDto
     */
    names: Array<string>;
}
